AddCSLuaFile("cl_init.lua")
AddCSLuaFile("shared.lua")
AddCSLuaFile("sh_config.lua")
AddCSLuaFile("player_class/player_csgo.lua")
AddCSLuaFile("client/cl_teams.lua")
AddCSLuaFile("client/cl_scoreboard.lua")
AddCSLuaFile("client/cl_bomb_notice.lua")
AddCSLuaFile("client/cl_round_hud.lua")
AddCSLuaFile("client/cl_killfeed.lua")
AddCSLuaFile("client/cl_rules.lua")

include("shared.lua")
include("server/sv_rules.lua")
include("server/sv_teams.lua")
include("server/sv_rounds.lua")
include("server/sv_killfeed.lua")
